### PR TITLE
Checking Qt version for PDF

### PR DESCRIPTION
**Pull request by ViniciusCampanha**

### CODE REVIEW

**Comment by ViniciusCampanha** [comment]
Jenkins rebuild

**Comment by ViniciusCampanha** [comment]
Jenkins rebuild

**Comment by ViniciusCampanha** [comment]
Jenkins rebuild

**Comment by janosimas** [comment]
jenkins rebuild

**Comment by ViniciusCampanha** [comment]
Jenkins rebuild

**Comment by ViniciusCampanha** [comment]
Jenkins rebuild

**Comment by ViniciusCampanha** [comment]
Jenkins rebuild

**Comment by ViniciusCampanha** [comment]
Jenkins rebuild

**Comment by ViniciusCampanha** [comment]
Jenkins rebuild

**Pull request closed without merging**
